---
tiitle: "ENGG 6150 term Project Proposal"
author:"Jian(Kevin), Lin"
output: word_document
---


Introduction:

Water quality is very crital to human health as well industrial processing. One of devices that can be used to determine water quality is turbidity meter.  Conventional turbidity measurement consists following steps. 

Traditional signal converter has five components:sensing element, signal conditioning, filter, analog to digital converter, microcontroller. In this project, direct digital readable sensors or quasi-digital sensor will be used. The output of this sensor is
microcontroller without using analog to digital converter. [1] In this paper, a turbidity meter prototype will be built. To achieve that, literatures will be reviewed and analyzed.

\newpage
Alt-Reference


[1] S. Ramesh, M. Sivaramakrishna, G. Rao. Design and development of a quasi-digital sensor and instrument for water turbidity measurement,Measurement Science and Technology, vol. 30, p. 115106, 2019 



lab 5:


when you measure turbidity of suspension, do not touch with hands, with out glass surface with Kimwipe. 

Turbidity unit is Nephelometric Turbidy Units. 

read up to lab 6. 

turn the meter I/O on, 

measurement is set to auto

it takes 12 seconds for teh reading to show, measurement is in unit 12 seconds, 



Design and development of a quasi-digital sensor
and instrument for water turbidity measurement

step 1: The sensing element of the turbididy is a photodiode.It transfer optical energy into electrical signal in the order of $\mu$A

step 2: a low-pass filter to remove noise, analog-to-digital converter to interface with a microcontroller. 

step 3: a microcontroller acquires, stores communicates to the computer and displays  turbidity value on an LCD. 

finish page 2

_____________________________________________________



Hi Kevin,

 

Attached is the lab manual for the wastewater treatment course I used to teach at Sheridan College. Have a look at Labs 5 and 6. Both used turbidity meters, so you can see two examples of their applications: Lab 5 for jar testing (i.e. flocculation), and Lab 6 for filtration. In both cases, the turbidity reading is used to determine the efficacy of the treatment in removing particulates from water.

 

Regards,

 

Rafael

 






Overview

Each student will choose a bio-instrument, study the relevant technologies, analyze the business potential for a new product, and develop a design concept for a new/improved product. Students should approach this project as if they were planning to start a company to produce their new product.

Design Project Requirements

Each student is expected to design and .build a Bio-instrumentation prototype. Projects must address the following three areas

• Market Analysis
o identify the market (potential customers) for your product
o identify businesses that do/could compete with your product
o prepare a business plan for a company to develop your product
• Technology Assessment

o identify existing technologies to address your chosen bio application o assess weaknesses/limitations of existing technologies

o research upcoming technologies to address weaknesses/limitations
o propose a new design/technology to advance your chosen bio application
• Product Design

o propose your developed product to address your chosen bio application o develop your design concept with technical illustrations, simulations, etc. o implement your product such that a prototype can be demonstrated.

All projects should address the basic elements of all three areas with reasonable in depth effort.

Design Project Deadlines

1	Design Component 1 – One Page Proposal	Feb 5, 20
2	Design Component 2 – Two Page Report of literatures survey including	Fe. 19, 20
	journal articles, News Magazines, or from the Internet	
3	Design Component 3 – Full Design of the Final Circuit of Prototype –	March 11, 20
	Two page Report	
4	Design Component 4 – Project Progress Update	April 1, 20
5	Oral Presentation followed by prototype demonstration	April 8, 20
6	Project report	April 15, 20




1
 
Presentation Guidelines

Each student must prepare and deliver a ~15 min presentation of his/her project to the class. Each student must cover the following aspects (you can adapt the order of presentation to your project)

• Motivation

o describe and quantify the application area or bio-instrumentation problem your project is addressing

o outline the “background”, related work done by others to solve the application/problem your project seeks to address

o define the challenges that your work will address (or open problems you plan to solve) o define the goals of your project and outline your methodology (how you planned your approach to solve the challenges)

• Technology review

o give detailed analysis of the technology(s) related to your project, highlighting strengths and weaknesses

o describe new and/or forthcoming technologies in the field
o (if applicable) describe the new technology you have developed to enable your product

• Business/market analysis

o identify companies working in the field of your project, highlighting strengths and weaknesses

o expand on market for your product (what is the cost or similar products, how many are sold annually, etc.)

• Product design
o describe in detail the product you have designed

o demonstrate how it solves the challenges and meets needs o describe and demonstrate the prototype you have developed

• Conclusion

o summarize the motivation for and results of your project, highlighting how you have solved key challenges and/or developed a new product that will have impact on bio-instrumentation field

Final Report Guidelines

Each student should submit one final report by email to the instructor by 12am on Wednesday April 15. The report should be type-written and should include a cover sheet with your project title, course number, your name and the instructor’s name. It should be generated in a single electronic file (PDF or MS Word) of reasonable size (~< 3MB). If you include any material from other sources (text, figure, etc.), you must provide a complete reference citation. The reports will be checked against Plagiarism. Also, please double check for typos and spelling mistakes as those will be graded and count toward your report grade.


2
 

The report should cover the same aspects outlined above for the presentation but written out in paragraph form and presented in a professional manner. Try to keep your reports as concise as possible while still providing the necessary details to understand the motivation, methodology, and results of your research and design efforts. Include figures, embedded or appended, with descriptive captions, to enhance your description or highlight features of your work.

Formatting

While there are no specific formatting requirements, you are encouraged to make your report look professional and easy to read. Use tables, figures, etc. to highlight important features of your work and break up long sections of text. Single or 1.5 line spacing and 10-12 point fonts are generally preferable. Good organization and clearly identifiable headings for sections and sub-sections are encouraged.

Grading

Design projects are 55% of your overall grade. Overall project grades will be divided into the following components

55% Project Quality and prototype	25% Presentation	20% Report





































3
