---
tiitle: "ENGG 6150 term Project Proposal"
author:"Jian(Kevin), Lin"
output: word_document
---


Circuit Design:

There are two turbididty sensors have been used in this project.

```{r}
brand    <- c("KEYESTUDIO","Hilitand")
Operating_Voltage  <- c("DC 5V","DC 5V")
Operating_current <- c("11mA","30mA")
detection_Range <-c ("0-4550NTU",)
Principle <- c("convert current signal into voltage output through circuit")
```

*Definition:*

Phototransistor which is used to collect lights.  If light density is hihger, it wil have hight signal. After it collects the light, it will generate current. It can be collected to a resistor followed by op-amp to boost signal. The output of phototransitor is defined as base area of it and current gain of transitor.    

photoresistor is the component that connects to the phototransistor. 

photodiodes is used to convert light into current because emitted sun light has photon. Photon is converted into electron which generates current. That's also the princinple of converting solar energy into electricity.


    Principle of turbidity meter sensor is to use optic principle to estimate transmittance rate and scattering rate. It's similar to spectrometer which detects optical density. Water serves as blank for turbidity measurement. Sample has higher amount of haze will increase light transmittance meaning the turbidity sensor is high. Sample with lower amount of haze will have lower reading from turbididty sensor. The unit for turbidity meter is NTU.


   The general flow of detecting equipment is sensing element, signal conditioning, filter, analog to digital converter and microcontroler. 




Alt-Reference


[1] S. Ramesh, M. Sivaramakrishna, G. Rao. Design and development of a quasi-digital sensor and instrument for water turbidity measurement,Measurement Science and Technology, vol. 30, p. 115106, 2019 



