---
title: "Bininstrumentation Assignment 1 Answer Version 1"
author: "Kevin Lin"
date: "03/08/2020"
output: word_document
---


**Problem 1**

**Definitions of below items:**

**Measurand:**    
While measuring the quantity of an object, the quantity is used to symbolize the value. 
The object is referred to measurand. A particular object ,it's physically value is being measured by transducer and 
be quantified. This process is called measurant. It includes desired input and object of measurement. 


**Direct operational mode:**   
It can directly communicate through terminal.


**Invasive and non-invasive:**  
non-Invasive sensors is device that do not require biofluids by take samples from human body. Optical transducer is one of them. 


**Generating mode:**  
To be developed more....

	

**Real-time measurements:**   
It's the value of intentianlly measured object at time of measurement. 


**Interfering input:**   
It's a built-in unsensitive parameter that is unintentionally as instrument needs. To be developed more...


**Correlation coefficient:**   
It's a value that represents how two variables are related to each other. For instance, one variable(x1) has
value of a set of value ( 1, 2 ,3 4) and the other variable has value of (2,4,6,8). It can be concluded that these two variables are 
highly correlated as variable 2 just muliplication of variable 2. 

**Zero drift:**   
microvolt offset and nanovolt offset of instrument which will increase accuracy. It refers to small change of measurand. 


**problem 2:**      
refer to attached A1_answer.m

**problem 3:**  
To be continued

